version: 2.1

orbs:
  codecov: codecov/codecov@1.1.0

executors:
  cif_executor:
    docker:
      - image: circleci/openjdk:11-jdk-node

jobs:
  build:
    executor: cif_executor
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Update permissions
          command: sudo chown -R circleci /usr/local/lib/node_modules
      - run:
          name: Build
          command: |
            java -version
            mvn -v
            mvn -B clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}
      - store_test_results:
          path: core/target/surefire-reports
      - store_artifacts:
          path: core/target/surefire-reports
      - codecov/upload:
          flags: unittests

  build-classic:
    executor: cif_executor
    steps:
      - checkout
      - restore_cache:
          keys: 
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Update permissions
          command: sudo chown -R circleci /usr/local/lib/node_modules
      - run:
          name: Build
          command: |
            java -version
            mvn -v
            mvn -B clean install -Pclassic
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ checksum "pom.xml" }}

  start-magento:
    executor: cif_executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Magento and install sample content
          working_directory: .circleci
          command: bash install-magento.sh

  deploy-sample:
    executor: cif_executor

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ checksum "pom.xml" }}
            - maven-repo-v1-
      - run:
          name: Deploy Venia Sample Project to GitHub
          command: node .circleci/ci/deploy-venia.js

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-classic:
          filters:
            tags:
              only: /.*/
      - start-magento:
          filters:
            tags:
              only: /.*/
      - deploy-sample:
          requires:
            - build
            - build-classic
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^venia(-classic)?-\d+\.\d+\.\d+$/
